##############################
# App Definition
app: speak-memo
component: web
core: speak
version: 1.0.3

##############################
# Definition of the Secret
secret:
  - name: rabbitmq
    type: Opaque
    data:
      RABBITMQ_DEFAULT_USER: cmFiYml0bXE= # rabbitmq
      RABBITMQ_DEFAULT_PASS: U3ZjUmFiYml0TXE= # SvcRabbitMq

  - name: minio
    type: Opaque
    data:
      MINIO_ROOT_USER: bWluaW8= #minio
      MINIO_ROOT_PASSWORD: TWluaW9TM1N1Y2Nlc3M= #MinioS3Success

##############################
# Definition of the Deployment
deployment:
  replicas: 1
  revisionHistoryLimit: 3
  sendlogs: "true"
  stack: speak
  lbtype: internal
  affinity:
    - apps: services
  containers:
    - name: speak-memo
      image: ghcr.io/didevlab/
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "512Mi"
          cpu: "1"
      env:
        - name: TZ
          value: "America/Sao_Paulo"
        - name: PORT
          value: "80"

        # RabbitMQ
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq.rabbitmq.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_VHOST
          value: "syrin"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: s-rabbitmq
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: s-rabbitmq
              key: RABBITMQ_DEFAULT_PASS
        - name: QUEUE_NAME
          value: "00_speak_memo_audio_process_play"

        # MinIO
        - name: MINIO_URL
          value: "192.168.15.150"
        - name: MINIO_PORT
          value: "30002"
        - name: MINIO_BUCKET
          value: "speakmemo"
        - name: MINIO_BASE_PATH
          value: "queue-play"
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: s-minio
              key: MINIO_ROOT_USER #MINIO_ACCESS_KEY
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s-minio
              key: MINIO_ROOT_PASSWORD #MINIO_SECRET_KEY


###########################
# Definition of the Service
services:
  - type: ClusterIP
    selector:
      app: speak-memo
      component: web
    ports:
      - name: speak-memo-tcp
        port: 80
        targetPort: 80
        protocol: TCP

  - type: NodePort
    selector:
      app: speak-memo
      component: web
    ports:
      - name: speak-memo-tcp
        nodePort: 30089
        port: 80
        targetPort: 80
        protocol: TCP